version: "3.9"
services:
  appflask:
    build: .
    ports:
      - "5000:5000"
    links:
      - mysqlcontenedor
    environment:
      - SECRET_KEY=ultrasecretkey
      - SQL_HOST=mysqlcontenedor
      - SQL_PORT=5000
      - SQL_USER=root
      - SQL_PASSWORD=1234
      - SQL_DATABASE=pruebadb
    depends_on:
      mysqlcontenedor:
        condition: service_healthy

  mysqlcontenedor:
    image: mysql:oraclelinux9
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pruebadb
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
